//   ==================================================================
//   >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
//   ------------------------------------------------------------------
//   Copyright (c) 2006 by Lattice Semiconductor Corporation
//   ------------------------------------------------------------------
//
//   IMPORTANT: THIS FILE IS AUTO-GENERATED BY THE LatticeMico32 System.
//
//   Permission:
//
//      Lattice Semiconductor grants permission to use this code
//      via the Lattice Open IP core license agreement.  Other use
//      of this code, including the selling or duplication of any
//      portion is strictly prohibited.
//
//   Disclaimer:
//
//      Lattice Semiconductor provides no warranty regarding the use or
//      functionality of this code. It is the user's responsibility to
//      verify their design for consistency and functionality through
//      the use of formal verification methods.
//
//   --------------------------------------------------------------------
//
//                  Lattice Semiconductor Corporation
//                  5555 NE Moore Court
//                  Hillsboro, OR 97214
//                  U.S.A
//
//                  TEL: 1-800-Lattice (USA and Canada)
//                         503-286-8001 (other locations)
//
//                  web: http://www.latticesemi.com/
//                  email: techsupport@latticesemi.com
//
//   --------------------------------------------------------------------
//
//      Project:           ztex_spartan6
//      File:              ztex_spartan6_inst.v
//      Date:              to, 24 feb 2011 21:55:22 GMT
//      Version:           8.1.01.28
//      Targeted Family:   EC
//
//   =======================================================================

`include "../components/lm32_top/rtl/verilog/lm32_include_all.v"
`include "../components/wb_ebr_ctrl/rtl/verilog/wb_ebr_ctrl.v"
`include "../components/gpio/rtl/verilog/gpio.v"
`include "../components/gpio/rtl/verilog/tpio.v"
ztex_spartan6 ztex_spartan6_u ( 
.clk_i(clk_i),
.reset_n(reset_n)
, .gpioPIO_OUT(gpioPIO_OUT) // [8-1:0]
);
